/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';

export namespace Components {
  interface AppAbout {}
  interface AppBignumbers {}
  interface AppHeropage {
    'match': MatchResults;
  }
  interface AppHome {}
  interface AppRoot {}
  interface MnvAnchor {
    'href': string;
  }
  interface MnvBase {}
  interface MnvBignumber {}
  interface MnvButton {
    'contained': boolean;
    'disabled': boolean;
    'full': boolean;
    'marginzero': boolean;
    'outlined': boolean;
    'type': string;
  }
  interface MnvCard {
    'button': string;
    'overline': string;
    'subtitle': string;
    'title': string;
  }
  interface MnvCol {
    'class': string;
  }
  interface MnvContainer {
    'lg': number;
    'md': number;
    'sm': number;
    'xl': number;
    'xs': number;
  }
  interface MnvDivider {}
  interface MnvDrawermobile {
    'open': boolean;
  }
  interface MnvFigure {
    'alt': string;
    'src': string;
  }
  interface MnvFigureCaption {
    'alt': string;
    'bold': boolean;
    'boldspotlight': boolean;
    'boldtext': boolean;
    'italic': boolean;
    'italicspotlight': boolean;
    'italictext': boolean;
    'src': string;
  }
  interface MnvFooter {}
  interface MnvGrid {
    'container': boolean;
    'indented': boolean;
    'item': boolean;
    'lg': string;
    'md': string;
    'sm': string;
    'spacing': number;
    'xl': string;
  }
  interface MnvHero {
    'background': string;
    'bgimg': string;
    'button': string;
    'herotitle': string;
  }
  interface MnvIconbutton {
    'disabled': boolean;
    'type': string;
  }
  interface MnvLink {
    'href': string;
  }
  interface MnvMark {}
  interface MnvMenubuttonmobile {
    'open': boolean;
  }
  interface MnvMenumobile {
    'hover': boolean;
    'open': boolean;
  }
  interface MnvNavbar {
    'setClass': string;
  }
  interface MnvNavbutton {
    'contained': boolean;
    'disabled': boolean;
    'marginzero': boolean;
    'outlined': boolean;
    'type': string;
  }
  interface MnvOverline {}
  interface MnvParagraph {
    /**
    * Altera o parágrafo para tamanho reduzido (body 2).
    */
    'bodytwo': boolean;
    /**
    * Ativa ou desativa estilização de capitular.
    */
    'capitular': boolean;
  }
  interface MnvPre {}
  interface MnvRow {}
  interface MnvStrong {}
  interface MnvSubtitle {
    'type': string;
  }
  interface MnvTitle {
    'level': string;
    'overline': string;
  }
  interface MnvTooltip {
    'label': string;
    'length': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLAppAboutElement extends Components.AppAbout, HTMLStencilElement {}
  var HTMLAppAboutElement: {
    prototype: HTMLAppAboutElement;
    new (): HTMLAppAboutElement;
  };

  interface HTMLAppBignumbersElement extends Components.AppBignumbers, HTMLStencilElement {}
  var HTMLAppBignumbersElement: {
    prototype: HTMLAppBignumbersElement;
    new (): HTMLAppBignumbersElement;
  };

  interface HTMLAppHeropageElement extends Components.AppHeropage, HTMLStencilElement {}
  var HTMLAppHeropageElement: {
    prototype: HTMLAppHeropageElement;
    new (): HTMLAppHeropageElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLMnvAnchorElement extends Components.MnvAnchor, HTMLStencilElement {}
  var HTMLMnvAnchorElement: {
    prototype: HTMLMnvAnchorElement;
    new (): HTMLMnvAnchorElement;
  };

  interface HTMLMnvBaseElement extends Components.MnvBase, HTMLStencilElement {}
  var HTMLMnvBaseElement: {
    prototype: HTMLMnvBaseElement;
    new (): HTMLMnvBaseElement;
  };

  interface HTMLMnvBignumberElement extends Components.MnvBignumber, HTMLStencilElement {}
  var HTMLMnvBignumberElement: {
    prototype: HTMLMnvBignumberElement;
    new (): HTMLMnvBignumberElement;
  };

  interface HTMLMnvButtonElement extends Components.MnvButton, HTMLStencilElement {}
  var HTMLMnvButtonElement: {
    prototype: HTMLMnvButtonElement;
    new (): HTMLMnvButtonElement;
  };

  interface HTMLMnvCardElement extends Components.MnvCard, HTMLStencilElement {}
  var HTMLMnvCardElement: {
    prototype: HTMLMnvCardElement;
    new (): HTMLMnvCardElement;
  };

  interface HTMLMnvColElement extends Components.MnvCol, HTMLStencilElement {}
  var HTMLMnvColElement: {
    prototype: HTMLMnvColElement;
    new (): HTMLMnvColElement;
  };

  interface HTMLMnvContainerElement extends Components.MnvContainer, HTMLStencilElement {}
  var HTMLMnvContainerElement: {
    prototype: HTMLMnvContainerElement;
    new (): HTMLMnvContainerElement;
  };

  interface HTMLMnvDividerElement extends Components.MnvDivider, HTMLStencilElement {}
  var HTMLMnvDividerElement: {
    prototype: HTMLMnvDividerElement;
    new (): HTMLMnvDividerElement;
  };

  interface HTMLMnvDrawermobileElement extends Components.MnvDrawermobile, HTMLStencilElement {}
  var HTMLMnvDrawermobileElement: {
    prototype: HTMLMnvDrawermobileElement;
    new (): HTMLMnvDrawermobileElement;
  };

  interface HTMLMnvFigureElement extends Components.MnvFigure, HTMLStencilElement {}
  var HTMLMnvFigureElement: {
    prototype: HTMLMnvFigureElement;
    new (): HTMLMnvFigureElement;
  };

  interface HTMLMnvFigureCaptionElement extends Components.MnvFigureCaption, HTMLStencilElement {}
  var HTMLMnvFigureCaptionElement: {
    prototype: HTMLMnvFigureCaptionElement;
    new (): HTMLMnvFigureCaptionElement;
  };

  interface HTMLMnvFooterElement extends Components.MnvFooter, HTMLStencilElement {}
  var HTMLMnvFooterElement: {
    prototype: HTMLMnvFooterElement;
    new (): HTMLMnvFooterElement;
  };

  interface HTMLMnvGridElement extends Components.MnvGrid, HTMLStencilElement {}
  var HTMLMnvGridElement: {
    prototype: HTMLMnvGridElement;
    new (): HTMLMnvGridElement;
  };

  interface HTMLMnvHeroElement extends Components.MnvHero, HTMLStencilElement {}
  var HTMLMnvHeroElement: {
    prototype: HTMLMnvHeroElement;
    new (): HTMLMnvHeroElement;
  };

  interface HTMLMnvIconbuttonElement extends Components.MnvIconbutton, HTMLStencilElement {}
  var HTMLMnvIconbuttonElement: {
    prototype: HTMLMnvIconbuttonElement;
    new (): HTMLMnvIconbuttonElement;
  };

  interface HTMLMnvLinkElement extends Components.MnvLink, HTMLStencilElement {}
  var HTMLMnvLinkElement: {
    prototype: HTMLMnvLinkElement;
    new (): HTMLMnvLinkElement;
  };

  interface HTMLMnvMarkElement extends Components.MnvMark, HTMLStencilElement {}
  var HTMLMnvMarkElement: {
    prototype: HTMLMnvMarkElement;
    new (): HTMLMnvMarkElement;
  };

  interface HTMLMnvMenubuttonmobileElement extends Components.MnvMenubuttonmobile, HTMLStencilElement {}
  var HTMLMnvMenubuttonmobileElement: {
    prototype: HTMLMnvMenubuttonmobileElement;
    new (): HTMLMnvMenubuttonmobileElement;
  };

  interface HTMLMnvMenumobileElement extends Components.MnvMenumobile, HTMLStencilElement {}
  var HTMLMnvMenumobileElement: {
    prototype: HTMLMnvMenumobileElement;
    new (): HTMLMnvMenumobileElement;
  };

  interface HTMLMnvNavbarElement extends Components.MnvNavbar, HTMLStencilElement {}
  var HTMLMnvNavbarElement: {
    prototype: HTMLMnvNavbarElement;
    new (): HTMLMnvNavbarElement;
  };

  interface HTMLMnvNavbuttonElement extends Components.MnvNavbutton, HTMLStencilElement {}
  var HTMLMnvNavbuttonElement: {
    prototype: HTMLMnvNavbuttonElement;
    new (): HTMLMnvNavbuttonElement;
  };

  interface HTMLMnvOverlineElement extends Components.MnvOverline, HTMLStencilElement {}
  var HTMLMnvOverlineElement: {
    prototype: HTMLMnvOverlineElement;
    new (): HTMLMnvOverlineElement;
  };

  interface HTMLMnvParagraphElement extends Components.MnvParagraph, HTMLStencilElement {}
  var HTMLMnvParagraphElement: {
    prototype: HTMLMnvParagraphElement;
    new (): HTMLMnvParagraphElement;
  };

  interface HTMLMnvPreElement extends Components.MnvPre, HTMLStencilElement {}
  var HTMLMnvPreElement: {
    prototype: HTMLMnvPreElement;
    new (): HTMLMnvPreElement;
  };

  interface HTMLMnvRowElement extends Components.MnvRow, HTMLStencilElement {}
  var HTMLMnvRowElement: {
    prototype: HTMLMnvRowElement;
    new (): HTMLMnvRowElement;
  };

  interface HTMLMnvStrongElement extends Components.MnvStrong, HTMLStencilElement {}
  var HTMLMnvStrongElement: {
    prototype: HTMLMnvStrongElement;
    new (): HTMLMnvStrongElement;
  };

  interface HTMLMnvSubtitleElement extends Components.MnvSubtitle, HTMLStencilElement {}
  var HTMLMnvSubtitleElement: {
    prototype: HTMLMnvSubtitleElement;
    new (): HTMLMnvSubtitleElement;
  };

  interface HTMLMnvTitleElement extends Components.MnvTitle, HTMLStencilElement {}
  var HTMLMnvTitleElement: {
    prototype: HTMLMnvTitleElement;
    new (): HTMLMnvTitleElement;
  };

  interface HTMLMnvTooltipElement extends Components.MnvTooltip, HTMLStencilElement {}
  var HTMLMnvTooltipElement: {
    prototype: HTMLMnvTooltipElement;
    new (): HTMLMnvTooltipElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'app-about': HTMLAppAboutElement;
    'app-bignumbers': HTMLAppBignumbersElement;
    'app-heropage': HTMLAppHeropageElement;
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'mnv-anchor': HTMLMnvAnchorElement;
    'mnv-base': HTMLMnvBaseElement;
    'mnv-bignumber': HTMLMnvBignumberElement;
    'mnv-button': HTMLMnvButtonElement;
    'mnv-card': HTMLMnvCardElement;
    'mnv-col': HTMLMnvColElement;
    'mnv-container': HTMLMnvContainerElement;
    'mnv-divider': HTMLMnvDividerElement;
    'mnv-drawermobile': HTMLMnvDrawermobileElement;
    'mnv-figure': HTMLMnvFigureElement;
    'mnv-figure-caption': HTMLMnvFigureCaptionElement;
    'mnv-footer': HTMLMnvFooterElement;
    'mnv-grid': HTMLMnvGridElement;
    'mnv-hero': HTMLMnvHeroElement;
    'mnv-iconbutton': HTMLMnvIconbuttonElement;
    'mnv-link': HTMLMnvLinkElement;
    'mnv-mark': HTMLMnvMarkElement;
    'mnv-menubuttonmobile': HTMLMnvMenubuttonmobileElement;
    'mnv-menumobile': HTMLMnvMenumobileElement;
    'mnv-navbar': HTMLMnvNavbarElement;
    'mnv-navbutton': HTMLMnvNavbuttonElement;
    'mnv-overline': HTMLMnvOverlineElement;
    'mnv-paragraph': HTMLMnvParagraphElement;
    'mnv-pre': HTMLMnvPreElement;
    'mnv-row': HTMLMnvRowElement;
    'mnv-strong': HTMLMnvStrongElement;
    'mnv-subtitle': HTMLMnvSubtitleElement;
    'mnv-title': HTMLMnvTitleElement;
    'mnv-tooltip': HTMLMnvTooltipElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface AppAbout extends JSXBase.HTMLAttributes<HTMLAppAboutElement> {}
  interface AppBignumbers extends JSXBase.HTMLAttributes<HTMLAppBignumbersElement> {}
  interface AppHeropage extends JSXBase.HTMLAttributes<HTMLAppHeropageElement> {
    'match'?: MatchResults;
  }
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface MnvAnchor extends JSXBase.HTMLAttributes<HTMLMnvAnchorElement> {
    'href'?: string;
  }
  interface MnvBase extends JSXBase.HTMLAttributes<HTMLMnvBaseElement> {}
  interface MnvBignumber extends JSXBase.HTMLAttributes<HTMLMnvBignumberElement> {}
  interface MnvButton extends JSXBase.HTMLAttributes<HTMLMnvButtonElement> {
    'contained'?: boolean;
    'disabled'?: boolean;
    'full'?: boolean;
    'marginzero'?: boolean;
    'outlined'?: boolean;
    'type'?: string;
  }
  interface MnvCard extends JSXBase.HTMLAttributes<HTMLMnvCardElement> {
    'button'?: string;
    'overline'?: string;
    'subtitle'?: string;
    'title'?: string;
  }
  interface MnvCol extends JSXBase.HTMLAttributes<HTMLMnvColElement> {
    'class'?: string;
  }
  interface MnvContainer extends JSXBase.HTMLAttributes<HTMLMnvContainerElement> {
    'lg'?: number;
    'md'?: number;
    'sm'?: number;
    'xl'?: number;
    'xs'?: number;
  }
  interface MnvDivider extends JSXBase.HTMLAttributes<HTMLMnvDividerElement> {}
  interface MnvDrawermobile extends JSXBase.HTMLAttributes<HTMLMnvDrawermobileElement> {
    'open'?: boolean;
  }
  interface MnvFigure extends JSXBase.HTMLAttributes<HTMLMnvFigureElement> {
    'alt'?: string;
    'src'?: string;
  }
  interface MnvFigureCaption extends JSXBase.HTMLAttributes<HTMLMnvFigureCaptionElement> {
    'alt'?: string;
    'bold'?: boolean;
    'boldspotlight'?: boolean;
    'boldtext'?: boolean;
    'italic'?: boolean;
    'italicspotlight'?: boolean;
    'italictext'?: boolean;
    'src'?: string;
  }
  interface MnvFooter extends JSXBase.HTMLAttributes<HTMLMnvFooterElement> {}
  interface MnvGrid extends JSXBase.HTMLAttributes<HTMLMnvGridElement> {
    'container'?: boolean;
    'indented'?: boolean;
    'item'?: boolean;
    'lg'?: string;
    'md'?: string;
    'sm'?: string;
    'spacing'?: number;
    'xl'?: string;
  }
  interface MnvHero extends JSXBase.HTMLAttributes<HTMLMnvHeroElement> {
    'background'?: string;
    'bgimg'?: string;
    'button'?: string;
    'herotitle'?: string;
  }
  interface MnvIconbutton extends JSXBase.HTMLAttributes<HTMLMnvIconbuttonElement> {
    'disabled'?: boolean;
    'type'?: string;
  }
  interface MnvLink extends JSXBase.HTMLAttributes<HTMLMnvLinkElement> {
    'href'?: string;
  }
  interface MnvMark extends JSXBase.HTMLAttributes<HTMLMnvMarkElement> {}
  interface MnvMenubuttonmobile extends JSXBase.HTMLAttributes<HTMLMnvMenubuttonmobileElement> {
    'open'?: boolean;
  }
  interface MnvMenumobile extends JSXBase.HTMLAttributes<HTMLMnvMenumobileElement> {
    'hover'?: boolean;
    'onBackgroundToggle'?: (event: CustomEvent<any>) => void;
    'open'?: boolean;
  }
  interface MnvNavbar extends JSXBase.HTMLAttributes<HTMLMnvNavbarElement> {
    'setClass'?: string;
  }
  interface MnvNavbutton extends JSXBase.HTMLAttributes<HTMLMnvNavbuttonElement> {
    'contained'?: boolean;
    'disabled'?: boolean;
    'marginzero'?: boolean;
    'outlined'?: boolean;
    'type'?: string;
  }
  interface MnvOverline extends JSXBase.HTMLAttributes<HTMLMnvOverlineElement> {}
  interface MnvParagraph extends JSXBase.HTMLAttributes<HTMLMnvParagraphElement> {
    /**
    * Altera o parágrafo para tamanho reduzido (body 2).
    */
    'bodytwo'?: boolean;
    /**
    * Ativa ou desativa estilização de capitular.
    */
    'capitular'?: boolean;
  }
  interface MnvPre extends JSXBase.HTMLAttributes<HTMLMnvPreElement> {}
  interface MnvRow extends JSXBase.HTMLAttributes<HTMLMnvRowElement> {}
  interface MnvStrong extends JSXBase.HTMLAttributes<HTMLMnvStrongElement> {}
  interface MnvSubtitle extends JSXBase.HTMLAttributes<HTMLMnvSubtitleElement> {
    'type'?: string;
  }
  interface MnvTitle extends JSXBase.HTMLAttributes<HTMLMnvTitleElement> {
    'level'?: string;
    'overline'?: string;
  }
  interface MnvTooltip extends JSXBase.HTMLAttributes<HTMLMnvTooltipElement> {
    'label'?: string;
    'length'?: string;
  }
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'app-about': AppAbout;
    'app-bignumbers': AppBignumbers;
    'app-heropage': AppHeropage;
    'app-home': AppHome;
    'app-root': AppRoot;
    'mnv-anchor': MnvAnchor;
    'mnv-base': MnvBase;
    'mnv-bignumber': MnvBignumber;
    'mnv-button': MnvButton;
    'mnv-card': MnvCard;
    'mnv-col': MnvCol;
    'mnv-container': MnvContainer;
    'mnv-divider': MnvDivider;
    'mnv-drawermobile': MnvDrawermobile;
    'mnv-figure': MnvFigure;
    'mnv-figure-caption': MnvFigureCaption;
    'mnv-footer': MnvFooter;
    'mnv-grid': MnvGrid;
    'mnv-hero': MnvHero;
    'mnv-iconbutton': MnvIconbutton;
    'mnv-link': MnvLink;
    'mnv-mark': MnvMark;
    'mnv-menubuttonmobile': MnvMenubuttonmobile;
    'mnv-menumobile': MnvMenumobile;
    'mnv-navbar': MnvNavbar;
    'mnv-navbutton': MnvNavbutton;
    'mnv-overline': MnvOverline;
    'mnv-paragraph': MnvParagraph;
    'mnv-pre': MnvPre;
    'mnv-row': MnvRow;
    'mnv-strong': MnvStrong;
    'mnv-subtitle': MnvSubtitle;
    'mnv-title': MnvTitle;
    'mnv-tooltip': MnvTooltip;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


